MAINTAINERCLEANFILES = Makefile.in

noinst_SCRIPTS = CallbackTest2 CallDataTest4 crMovesText1 DtCursorTest2 \
		 DtWsTest1 EventHandlerTest ListBounds1 ListItemPos1 PopupTest \
		 SelBoxResTest SessionTest TextCutBuf1 TextDisp1 TextFXYPos1 \
		 TransEventTest TransTest1 WorkProcTest1 XdrawTest

CLEANFILES = $(noinst_SCRIPTS)
